apiVersion: v1
kind: Pod
metadata:
  name: startup-probe-http
spec:
  containers:
    - name: startup-nginx
      image: k8s.gcr.io/nginx
      startupProbe:
        httpGet:
          path: /
          port: 80
        failureThreshold: 30
        periodSeconds: 10
