apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
          command:
            - /bin/sh
          args:
            - '-c'
            - echo "Hello from the Nginx container"; sleep 3600
        - name: busybox-container
          image: busybox:latest
          ports:
            - containerPort: 8081
          command:
            - /bin/sh
          args:
            - '-c'
            - echo "Hello from the Busybox container"; sleep 3600
