apiVersion: v1
kind: Pod
metadata:
  name: nginx_webproxy
  labels:
    app: nginx_pod
spec:
  containers:
  - name: nginx
    image: nginx:1.16.0
    ports:
    - name: nginx_port
      containerPort: 80
