apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginxpod
    #It (nginxpod) should be match with your pod manifest file. It will create a service for pod which has nginxpod
  ports:
  - protocol: TCP
    port: 80
    nodeport: 31010
    targetPort: nginxport
