apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginxpod  # Matches the label from the pod
  ports:
  - protocol: TCP
    port: 80        # Service port
    nodePort: 31010 # NodePort to expose the service
    targetPort: 80  # Actual container port, set to 80
  type: NodePort    # Ensures the service is exposed via a NodePort
