apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  # Define the Init Container
  initContainers:
    - name: init-setup
      image: busybox
      command: ['sh', '-c', 'echo "Setup completed at $(date)" > /mnt/volume/setup.txt']
      volumeMounts:
        - name: shared-data
          mountPath: /mnt/volume

  # Define the main application container
  containers:
    - name: main-app
      image: busybox
      command: ['sh', '-c', 'cat /mnt/volume/setup.txt && sleep 3600']
      volumeMounts:
        - name: shared-data
          mountPath: /mnt/volume

  # Define the volume to be shared between Init and main containers
  volumes:
    - name: shared-data
      emptyDir: {}
